version: 0.1

environment_variables:
  plaintext:
    FOO: "bar"

phases:
  install:
    commands:
      - cat /etc/lsb-release
      - apt-get update -y
      - apt-get install -y software-properties-common
      - apt-add-repository -y ppa:brightbox/ruby-ng
      - apt-get update -y
      - apt-get install -y ruby2.3 ruby2.3-dev
      - gem install --no-ri --no-rdoc ufo
      - curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ufo docker build
      - docker tag $(ufo docker image_name) hi_web
      - docker-compose run web bundle exec rake db:create db:migrate
      - docker-compose run web bundle exec rake
  post_build:
    commands:
      - echo Build completed on `date`
